# Generated by Django 5.2.9 on 2025-12-14 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='defect',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='comment',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defects.defect', verbose_name='Дефект'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='defects.defect', verbose_name='Дефект'),
        ),
        migrations.AddField(
            model_name='defect',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='defects.project', verbose_name='Проект'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['status', 'priority'], name='defects_def_status_82d729_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['deadline'], name='defects_def_deadlin_d368ad_idx'),
        ),
    ]
