# Generated by Django 5.2.9 on 2025-12-14 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('updated', 'Изменён'), ('status_changed', 'Изменён статус'), ('comment_added', 'Добавлен комментарий'), ('attachment_added', 'Добавлено вложение')], max_length=32, verbose_name='Событие')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения (diff)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_history_events', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='defects.defect', verbose_name='Дефект')),
            ],
            options={
                'verbose_name': 'История дефекта',
                'verbose_name_plural': 'История дефекта',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['defect', 'created_at'], name='defects_def_defect__e459c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='defects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проекта',
                'ordering': ('order', 'start_date', 'id'),
                'indexes': [models.Index(fields=['project', 'order'], name='defects_pro_project_98c759_idx')],
            },
        ),
    ]
